### ISSUE TITLE
NodeExec: Create task skeleton

### ISSUE THREAD

**Issue by invisible-arrow** [sivakumar-kailasam/gradle-npm-wrapper#1]
Create task skeleton as given [here](https://github.com/sivakumar-kailasam/gradle-npm-wrapper/wiki/Goals-of-this-plugin)

**Comment by sivakumar-kailasam** [comment]
Yep and make sure mandatory fields are asserted for. We should ensure that we group the tasks with a default name and let users override it if they want to.

**Comment by sivakumar-kailasam** [comment]
Lets leave out incremental build support. I'm guessing users can define this in their custom tasks. Everyone has a different setup for file organization and that is better left to users. Considering this what we have in our private setup,
```gradle
exec {
	workingDir "$projectDir"
	commandLine = generateCommandLineParams([nodeJsExecPath, "${nodeModulesPath}/less/bin/lessc", "-x", sourceFilePath, targetFilePath])
}
```

this could be simplified in this repo as,
```gradle
nodeExec {
          module = "lessc"
          command = "-x ${sourceFilePath} ${targetFilePath}"
}
```
